# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-22 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secrets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='total_likes',
        ),
        migrations.AddField(
            model_name='post',
            name='total_likes',
            field=models.IntegerField(default=0),
        ),
    ]
