# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-22 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0002_users_birthday'),
        ('secrets', '0002_auto_20170622_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='post_id',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='post',
            name='total_likes',
        ),
        migrations.AddField(
            model_name='post',
            name='user_likes',
            field=models.ManyToManyField(related_name='post_likes', to='reg.Users'),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
