# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-22 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secrets', '0003_auto_20170622_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='total_likes',
            field=models.IntegerField(default=0),
        ),
    ]
